### ISSUE TITLE
Graph does not update with state

### ISSUE THREAD

**Issue by guyzk** [aeyrium/bezier-chart#10]
I want to have a few graphs in separate cupertino segment.
When I switch between tabs the chart data is refreshed but the chart remains with the initial data (does not refresh - kind of like a singleton chart)
Each tab has a different date range (monthly, weekly etc...)

**Comment by diegoveloper** [comment]
Could you add a minimum sample code to reproduce the issue here?

**Comment by diegoveloper** [comment]
I updated the package, Could you try using the dependency in this way: 

```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```

And run :  `flutter packages upgrade`  

Let me know if it works.
