### ISSUE TITLE
Add callback for data point selection

### ISSUE THREAD

**Issue by Mazas17** [aeyrium/bezier-chart#12]
I would like to know when some point was selected and determine data of that point. Maybe you could add callback to BezierChartConfig?

**Comment by diegoveloper** [comment]
ok, and what if you display two lines inside the chart? Could be just one callback enough ? If that's the case I could add the callback inside `BezierChart` and it will return a value on each X datapoint (Only the DateTime or  Double if are using a non date chart)
.

**Comment by diegoveloper** [comment]
I updated the package, Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Check the method `sample3` from main sample.

```
onDateTimeSelected: (datetime) {
          print("selected datetime: $datetime");
        },
```
inside `BezierChart`

Let me knows if it works.
