### ISSUE TITLE
Labels on Y axis are overlaying

### ISSUE THREAD

**Issue by xylish7** [aeyrium/bezier-chart#18]
This problem was only mentioned in #4 , but it was not the main problem of the issue.

**Problem**:
![image](https://user-images.githubusercontent.com/24867712/61052673-93e33700-a3f4-11e9-9790-3a8b50ac7895.png)

**Desired output**:
It would be nice to show  only a number of labels choosed by the user.

**Example:** 
- lowestValue: 0
- highestValue:100
- labelsToShow: 5
![image](https://user-images.githubusercontent.com/24867712/61054289-d5c1ac80-a3f7-11e9-83e3-698a0184221c.png)

**Comment by diegoveloper** [comment]
Working on it :)

**Comment by diegoveloper** [comment]
Done,  I updated the code, Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Check the sample1 and sample7

Let me knows if it works.
