### ISSUE TITLE
Can't I have a selectedIndex?

### ISSUE THREAD

**Issue by zeucxb** [aeyrium/bezier-chart#31]
There are  something like selectedDate for CUSTOM?

**Comment by diegoveloper** [comment]
`selectedValue` was added on master version.

Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Check the sample1 , use it with `snap` true 

Let me knows if it works.
