### ISSUE TITLE
[Question] - Physics in ScrollView

### ISSUE THREAD

**Issue by LofOWL** [aeyrium/bezier-chart#41]
Hi there,
 Is it possible to switch physics in ScrollView into BouncingScrollPhysics()?

**Comment by diegoveloper** [comment]
ok, I sent some changes

Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

check the `sample3` , there is a new property for the config.
