### ISSUE TITLE
Weekly date format

### ISSUE THREAD

**Issue by guyzk** [aeyrium/bezier-chart#9]
it possible to add the month to the WEEKLY DateTime format?
Something like Tue 18/5 instead of Tue 18?
Or at least add an option for a format parameter.

It is necessary for a weekly chart over a span of 30 days for example:
fromDate is 18/5 and toDate is 17/6
Currently it is very difficult to know the day of which month you are currently viewing

**Comment by diegoveloper** [comment]
I updated the package, Could you try using the dependency in this way: 

```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```

And run :  `flutter packages upgrade`  

Check the method `sample3` from `main` sample.

Let me know if it works.
